trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'Installer'
    jdkInstallerMethod: 'Task'
    tasks: 'useJavaVersion'
    cleanDestinationDirectory: true

- script: 'mvn clean test'
  displayName: 'Run TestNG Tests'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    mergeTestResults: true
    testRunTitle: 'TestNG Test Run'